### ISSUE TITLE
Forward differentiation with Enzyme doesn't work

### ISSUE THREAD

**Issue by albertomercurio** [SciML/SciMLSensitivity.jl#1226]
**Describe the bug 🐞**

The _Reverse_ differentiation using **Enzyme.jl** of an ODE involving **SciMLOperators.jl** has been almost resolved #1139 #1225. I was trying to perform the _Forward_ differentiation instead, but it fails.

_Forward_ differentiation with **Enzyme.jl** would be very useful in all the cases where the ODE is ComplexF64 and **ForwardDiff.jl** cannot handle this.

**Expected behavior**

A correct value of the gradient or Jacobian.

**Minimal Reproducible Example 👇**

```julia
using LinearAlgebra
using SparseArrays
using OrdinaryDiffEq
using SciMLSensitivity
using SciMLOperators
using Enzyme

##

const T = ComplexF64

coef1(a, u, p, t) = -p[1]
coef2(a, u, p, t) = p[2]

A1_data = sparse(T[0.0 1.0; 0.0 0.0])
A2_data = sparse(T[0.0 0.0; 1.0 0.0])
c1 = ScalarOperator(one(T), coef1)
c2 = ScalarOperator(one(T), coef2)

const U = c1 * MatrixOperator(A1_data) + c2 * MatrixOperator(A2_data)

function my_fun(p)
    x = T[3.0, 4.0]
    prob = ODEProblem{true}(U, x, (0.0, 1.0), p)
    sol = solve(prob, Tsit5(), save_everystep=false,
        sensealg=ForwardSensitivity(),
    )
    return real(sol.u[end][end])
end

##

p = [1.0, 2.0]

dp = Enz[yme.make_zero(p)
Enzyme.autodiff(Enzyme.set_runtime_activity(Enzyme.Reverse), my_fun, Active, Duplicated(p, dp))
dp]([url](url))

dp = Enzyme.make_zero(p)
Enzyme.autodiff(Enzyme.set_runtime_activity(Enzyme.Forward), my_fun, Duplicated(p, dp))
dp
```

**Error & Stacktrace ⚠️**

```julia
ERROR: Error handling recursive stores for String which has a fieldcount of 0
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] create_recursive_stores(B::LLVM.IRBuilder, Ty::DataType, prev::LLVM.Value)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:622
  [3] create_recursive_stores(B::LLVM.IRBuilder, Ty::DataType, prev::LLVM.Value)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:667
  [4] shadow_alloc_rewrite(V::Ptr{…}, gutils::Ptr{…}, Orig::Ptr{…}, idx::UInt64, prev::Ptr{…}, used::UInt8)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:715
  [5] EnzymeCreateForwardDiff(logic::Enzyme.Logic, todiff::LLVM.Function, retType::Enzyme.API.CDIFFE_TYPE, constant_args::Vector{…}, TA::Enzyme.TypeAnalysis, returnValue::Bool, mode::Enzyme.API.CDerivativeMode, runtimeActivity::Bool, strongZero::Bool, width::Int64, additionalArg::Ptr{…}, typeInfo::Enzyme.FnTypeInfo, uncacheable_args::Vector{…})
    @ Enzyme.API ~/.julia/packages/Enzyme/MZ6Nf/src/api.jl:342
  [6] enzyme!(job::GPUCompiler.CompilerJob{…}, mod::LLVM.Module, primalf::LLVM.Function, TT::Type, mode::Enzyme.API.CDerivativeMode, width::Int64, parallel::Bool, actualRetType::Type, wrap::Bool, modifiedBetween::Tuple{…} where N, returnPrimal::Bool, expectedTapeType::Type, loweredArgs::Set{…}, boxedArgs::Set{…})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:1802
  [7] codegen(output::Symbol, job::GPUCompiler.CompilerJob{…}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:4702
  [8] codegen
    @ ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:3465 [inlined]
  [9] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:5563
 [10] _thunk
    @ ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:5563 [inlined]
 [11] cached_compilation
    @ ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:5615 [inlined]
 [12] thunkbase(mi::Core.MethodInstance, World::UInt64, FA::Type{…}, A::Type{…}, TT::Type, Mode::Enzyme.API.CDerivativeMode, width::Int64, ModifiedBetween::Tuple{…} where N, ReturnPrimal::Bool, ShadowInit::Bool, ABI::Type, ErrIfFuncWritten::Bool, RuntimeActivity::Bool, StrongZero::Bool, edges::Vector{…})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:5729
 [13] thunk_generator(world::UInt64, source::LineNumberNode, FA::Type, A::Type, TT::Type, Mode::Enzyme.API.CDerivativeMode, Width::Int64, ModifiedBetween::Tuple{…} where N, ReturnPrimal::Bool, ShadowInit::Bool, ABI::Type, ErrIfFuncWritten::Bool, RuntimeActivity::Bool, StrongZero::Bool, self::Any, fakeworld::Any, fa::Type, a::Type, tt::Type, mode::Type, width::Type, modifiedbetween::Type, returnprimal::Type, shadowinit::Type, abi::Type, erriffuncwritten::Type, runtimeactivity::Type, strongzero::Type)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/MZ6Nf/src/compiler.jl:5917
 [14] autodiff
    @ ~/.julia/packages/Enzyme/MZ6Nf/src/Enzyme.jl:654 [inlined]
 [15] autodiff
    @ ~/.julia/packages/Enzyme/MZ6Nf/src/Enzyme.jl:558 [inlined]
 [16] autodiff(mode::ForwardMode{false, FFIABI, false, true, false}, f::typeof(my_fun), args::Duplicated{Vector{Float64}})
    @ Enzyme ~/.julia/packages/Enzyme/MZ6Nf/src/Enzyme.jl:530
 [17] top-level scope
    @ ~/GitHub/Research/Undef/Autodiff QuantumToolbox/autodiff_ode.jl:91
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
(Autodiff QuantumToolbox) pkg> st
Status `~/GitHub/Research/Undef/Autodiff QuantumToolbox/Project.toml`
  [6e4b80f9] BenchmarkTools v1.6.0
  [a0c0ee7d] DifferentiationInterface v0.7.1
  [7da242da] Enzyme v0.13.51
  [26cc04aa] FiniteDifferences v0.12.32
  [f6369f11] ForwardDiff v1.0.1
  [b27dd330] GTPSA v1.4.7
  [1dea7af3] OrdinaryDiffEq v6.98.0
⌃ [6c2fb7c5] QuantumToolbox v0.32.0
⌅ [c0aeaf25] SciMLOperators v0.4.0
  [1ed8b502] SciMLSensitivity v7.86.1
  [e88e6eb3] Zygote v0.7.10
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

Same as #1225 

  - Output of `versioninfo()`

```julia
Julia Version 1.10.9
Commit 5595d20a287 (2025-03-10 12:51 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
Environment:
  JULIA_NUM_THREADS = auto
```

**Comment by wsmoses** [comment]
the string fieldcount zero issue was fixed upstream

**Comment by wsmoses** [comment]
that sounds like a potential issue in sciml code? @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
The MWE without SciMLSensitivity is just:

```julia
using LinearAlgebra
using SparseArrays
using OrdinaryDiffEq
using SciMLOperators
using Enzyme
const T = ComplexF64

coef1(a, u, p, t) = -p[1]
coef2(a, u, p, t) = p[2]

A1_data = sparse(T[0.0 1.0; 0.0 0.0])
A2_data = sparse(T[0.0 0.0; 1.0 0.0])
c1 = ScalarOperator(one(T), coef1)
c2 = ScalarOperator(one(T), coef2)

const U = c1 * MatrixOperator(A1_data) + c2 * MatrixOperator(A2_data)

function my_fun(p)
    x = T[3.0, 4.0]
    prob = ODEProblem{true}(U, x, (0.0, 1.0), p)
    sol = solve(prob, Tsit5(), save_everystep=false)
    return real(sol.u[end][end])
end

p = [1.0, 2.0]
dp = Enzyme.make_zero(p)
dp[1] = 1
my_fun(p) - my_fun(p .+ 1) # is a function of `p`

Enzyme.autodiff(Enzyme.set_runtime_activity(Enzyme.Forward), my_fun, Duplicated(p, dp))
dp
```

Note I get a stackoverflowerror when I run it on my windows machine, I didn't try any other. But notice this doesn't have any `using SciMLSensitivity` at all, it's just Enzyme Forward mode directly on the ODE solver. Enzyme Reverse hits SciMLSensitivity and replaces the autodiff with the adjoint method, while this is just purely autodiffing the solver. I don't have other tests on Forward mode autodiff of the solver, though https://github.com/EnzymeAD/Enzyme.jl/issues/2471 is quite related. 

But I think the "correctness" issue here was just an error on @albertomercurio's part. When doing the forward mode AD, you have to push forward some dual value. But he does `dp = Enzyme.make_zero(p)` and uses that. If all of the starting duals are zero then you will have that the output derivative is zero, so that's actually correct. You should test that it works out correctly, but since that wasn't compiling for me I created an MWE without the operators from the test case in the PR I linked and:

```julia
using Enzyme, OrdinaryDiffEq, StaticArrays

function lorenz!(du, u, p, t)
    du[1] = 10.0(u[2] - u[1])
    du[2] = u[1] * (28.0 - u[3]) - u[2]
    du[3] = u[1] * u[2] - (8 / 3) * u[3]
end

const _saveat =  SA[0.0,0.25,0.5,0.75,1.0,1.25,1.5,1.75,2.0,2.25,2.5,2.75,3.0]

function f(y::Array{Float64}, u0::Array{Float64})
    tspan = (0.0, 3.0)
    prob = ODEProblem{true, SciMLBase.FullSpecialize}(lorenz!, u0, tspan)
    sol = DiffEqBase.solve(prob, Tsit5(), saveat = _saveat, sensealg = DiffEqBase.SensitivityADPassThrough())
    y .= sol[1,:]
    return nothing
end;
u0 = [1.0; 0.0; 0.0]
d_u0 = zeros(3)
d_u0[1] = 1
y  = zeros(13)
dy = zeros(13)
p = Float64[]
dp = Float64[]

Enzyme.autodiff(Forward, f,  Duplicated(y, dy), Duplicated(u0, d_u0)); # This works!
```

it seems to work fine. 

So I think @albertomercurio's issue here was of interpretation. In Forward mode, you set the starting dual on `dp` and push it forward to the result. In Reverse mode, you go forwards, and then if you have a scalar Active return, you by default pullback in the dual space a `1.0`. So the Reverse mode code is calculating the gradient of the solution w.r.t. p and saving that to `dp`, while the forward mode code is calculating a direction derivative `d solution(T) / dp grad direction`, where the direction vector is 0, so it's appropriately zero. In the code I posted here I make the direction e_1, and I don't check the result directly but I presume that's working from my other test.

So I think everything is under control here.

**Comment by albertomercurio** [comment]
Thanks @ChrisRackauckas for pointing out this. However, I still get the wrong result. The `autodiff` function returns 0 and `dp` is still `[1, 0]`. I also tried the same problem without the use of SciMLOperators, and the result is still the same

```julia
using LinearAlgebra
using SparseArrays
using OrdinaryDiffEq
using Enzyme
const T = ComplexF64

const A1 = sparse(T[0.0 1.0; 0.0 0.0])
const A2 = sparse(T[0.0 0.0; 1.0 0.0])

function dudt!(du, u, p, t)
    mul!(du, A1, u, -p[1], zero(T))
    mul!(du, A2, u, p[2], one(T))
    return nothing
end

function my_fun2(p)
    x = T[3.0, 4.0]
    prob = ODEProblem{true}(dudt!, x, (0.0, 1.0), p)
    sol = solve(prob, Tsit5(), save_everystep=false)
    return real(sol.u[end][end])
end

# %%

p = [1.0, 2.0]

my_fun2(p) - my_fun2(p .+ 1)

dp = Enzyme.make_zero(p)
dp[1] = 1
Enzyme.autodiff(Enzyme.set_runtime_activity(Enzyme.Forward), my_fun2, Duplicated(p, dp)) # (0.0,)
dp
# 2-element Vector{Float64}:
#  1.0
#  0.0
```
